#Config File example
save_dir: /home/gbc/workspace/nanodet/wider_ped/test7_lr0032_eps280_bs32_brightness02                        #####
model:
  arch:
    name: OneStageDetector
    backbone:
      name: ShuffleNetV2
      model_size: 1.0x
      out_stages: [2,3,4]
      activation: LeakyReLU
    fpn:
      name: PAN
      in_channels: [116, 232, 464]
      out_channels: 96
      start_level: 0
      num_outs: 3
    head:
      name: NanoDetHead
      num_classes: 1                                                        #####
      input_channel: 96
      feat_channels: 96
      stacked_convs: 2
      share_cls_reg: True
      octave_base_scale: 5
      scales_per_octave: 1
      strides: [8, 16, 32]
      reg_max: 7
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0
data:
  train:
    name: wider_challenge
    img_path: /home/gbc/workspace/nanodet/data/images/sur_train             #####                              
    ann_path: /home/gbc/workspace/nanodet/data/annotations/sur_train.json   #####
    input_size: [320,320] #[w,h]
    keep_ratio: True
    pipeline:
      perspective: 0.0
      scale: [0.4, 1.6]                                                     #####
      stretch: [[1, 1], [1, 1]]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5                                                             # √
      brightness: 0.2                                                       # √
      contrast: [0.5, 1.5]                                                  # √
      saturation: [0.5, 1.5]                                                # √
      normalize: [[123.675, 116.28, 103.53], [58.395, 57.12, 57.375]]       # √
  val:
    name: wider_challenge
    img_path: /home/gbc/workspace/nanodet/data/images/val_data/sur_val      #####
    ann_path: /home/gbc/workspace/nanodet/data/annotations/sur_val.json     #####
    input_size: [320,320] #[w,h]
    keep_ratio: True
    pipeline:
      normalize: [[123.675, 116.28, 103.53], [58.395, 57.12, 57.375]]       # √
device:
  gpu_ids: [0]                                                              #####
  workers_per_gpu: 4
  batchsize_per_gpu: 32                                                    #%%%%%
schedule:
#  resume:
#  load_model: YOUR_MODEL_PATH
  optimizer:
    name: SGD
    lr: 0.032                                                                #%%%%%
    momentum: 0.9
    weight_decay: 0.0001
  warmup:
    name: linear
    steps: 300
    ratio: 0.1
  total_epochs: 280                                                         #%%%%
  lr_schedule:
    name: MultiStepLR
    milestones: [240,260,275]                                               #%%%%
    gamma: 0.1
  val_intervals: 10
evaluator:
  name: WiderPedDetectionEvaluator                                          #####
  save_key: mAP

log:
  interval: 10

class_names: ['pedestrain']
